name: st235.github.io
description: New Technology Blog 📔

highlighter: rouge
logo: false
paginate: 15
baseurl: /
#domain_name: 'http://github.io'
google_analytics: 'UA-112035371-1'

# Details for the RSS feed generator
url:            'st235.github.io'
author:         'Alexander Dadukin'
encoding: utf-8